version: '3.8'

services:
  app:
    build:
      context: .
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    image: terra-vigilance:latest
    ports:
      - "8080:80"
    container_name: terra-vigilance
    restart: unless-stopped
