name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: |
        az acr login --name acr48h

    - name: Create .env file with secrets
      run: |
        echo "VITE_GOOGLE_MAPS_API_KEY=${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}" > .env
        echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env
        echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env

    - name: Check .env contents
      run: cat .env

    - name: Build and push Docker image
      run: |
        export $(cat .env | xargs) && \
        docker build \
          --build-arg VITE_GOOGLE_MAPS_API_KEY=$VITE_GOOGLE_MAPS_API_KEY \
          --build-arg VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY \
          --build-arg VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
          -t acr48h.azurecr.io/terra-vigilance:v1 .

    - name: Restart container to apply new image
      run: |
        az container restart \
          --name terra-vigilance \
          --resource-group RG48h

    - name: Inspect built files inside Docker image
      run: |
        docker run --rm acr48h.azurecr.io/terra-vigilance:v1 grep -r 'supabase' /usr/share/nginx/html


    
